Repository rdkcentral/Dobby, pull requests merged in 2021-11, with the labels that each got.

#148 RDK-34228: Trusted apps can generate their own tokens
  bundle/runtime-schemas/defs-plugins.json
  rdkPlugins/Thunder/README.md
  rdkPlugins/Thunder/source/ThunderPlugin.cpp
  rdkPlugins/Thunder/source/ThunderPlugin.h
Labels: enhancement

#147 XIONE-6236 Don't wait for failed forks
  daemon/lib/source/DobbyRunC.cpp
Labels: bug

#150 XIONE-6236 Create timeout for RuncCreate
  daemon/lib/source/DobbyManager.cpp
  daemon/lib/source/DobbyRunC.cpp
  daemon/lib/source/DobbyRunC.h
Labels: bug

#152 RDK-34085: Release 3.1.0
  CMakeLists.txt
Labels: release

#155 XIONE-6749 Created high priority watchdog wagger
  daemon/lib/source/Dobby.cpp
Labels: bug

#156 RDKTV-12390: Handle long container log lines better with journald
  daemon/lib/source/DobbyLogger.cpp
  rdkPlugins/Logging/source/LoggingPlugin.cpp
  rdkPlugins/Logging/source/LoggingPlugin.h
Labels: bug
